### ISSUE TITLE
value isn't a "known" property on Promises in stache

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-reflect-promise#25]
```
Promise.prototype[Symbol.for("can.hasOwnKey")] = function(){
	return true;
}
```

**Comment by phillipskevin** [comment]
Shouldn't this just return `true` for these keys?

https://github.com/canjs/can-reflect-promise/blob/a1645ac078e5f388dba28090803f016c18bdc924/can-reflect-promise.js#L13-L20

**Comment by justinbmeyer** [comment]
It should

**Comment by justinbmeyer** [comment]
I wrote what’s up above as a hack
